name: Release

on: workflow_dispatch

permissions:
  contents: write
  discussions: write

env:
  PROJECT_NAME: BFEXEOPT

jobs:
  build:
    name: ${{ matrix.name }}

    strategy:
      matrix:
        include:
          - name: Android ARM64
            os: macos-15
            buildArgs: "android -final -ONLY_ARM64"
            artifactName: Android ARM64
            artifactPath: "export/release/android/bin/app/build/outputs/apk/release/*.apk"

          - name: Android ARMv7
            os: macos-15
            buildArgs: "android -final -ONLY_ARMV7"
            artifactName: Android ARMv7
            artifactPath: "export/release/android/bin/app/build/outputs/apk/release/*.apk"

    uses: ./.github/workflows/build.yml

    with:
      name: ${{ matrix.name }}
      os: ${{ matrix.os }}
      buildArgs: ${{ matrix.buildArgs }}
      artifactName: ${{ matrix.artifactName }}
      artifactPath: ${{ matrix.artifactPath }}

  Releaser:
    needs: [build]
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Download Android ARM64 Build
        uses: actions/download-artifact@main
        with:
          name: Android ARM64
          path: /home/runner

      - name: Move Android ARM64 File
        run: |
          mv /home/runner/${{ env.PROJECT_NAME }}-release.apk \
             /home/runner/${{ env.PROJECT_NAME }}-Android-ARM64.apk

      - name: Download Android ARMv7 Build
        uses: actions/download-artifact@main
        with:
          name: Android ARMv7
          path: /home/runner

      - name: Move Android ARMv7 File
        run: |
          mv /home/runner/${{ env.PROJECT_NAME }}-release.apk \
             /home/runner/${{ env.PROJECT_NAME }}-Android-ARMv7.apk

      - name: Publish The Release
        uses: softprops/action-gh-release@v2
        with:
          name: "BFEXEOPT"
          tag_name: "1.0.4"
          last_release: false
          files: |
            /home/runner/*.apk
